name: Pipeline with Build and Jest Test in 2 Jobs

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Running build
              run: npm run build
            - uses: actions/upload-artifact@v4
              with:
                  name: .next
                  path: .next
            - uses: actions/upload-artifact@v4
              with:
                  name: node_modules
                  path: node_modules
            - name: List files
              run: ls -R


    tests:
        runs-on: ubuntu-22.04
        needs: build # Test-Job wartet, bis der Build-Job erfolgreich ist
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - uses: actions/download-artifact@v4
              with:
                  name: .next
            - uses: actions/download-artifact@v4
              with:
                  name: node_modules
            - name: Npm runs the test
              run: npm test